import type { Metadata } from "next";
import { cookies, headers } from "next/headers";
import { redirect } from "next/navigation";
import "./globals.css";
import { isDevAuthBypassEnabled } from "./lib/devAuth";
import { getHrkpisSessionCookieName, readHrkpisSession } from "./lib/hrkpisSession";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const HRKPIS_LOGIN_PATH = process.env.HRKPIS_LOGIN_URL || "/hrkpis/login.php";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const sessionId = cookieStore.get(getHrkpisSessionCookieName())?.value;
  const session = await readHrkpisSession(sessionId);

  if (!session && !isDevAuthBypassEnabled) {
    // Must be an absolute URL: redirect() auto-prefixes relative paths with
    // basePath, which would wrongly turn /hrkpis/login.php into /recognitionCard/hrkpis/login.php.
    if (/^https?:\/\//.test(HRKPIS_LOGIN_PATH)) {
      redirect(HRKPIS_LOGIN_PATH);
    }
    const headerList = await headers();
    const host = headerList.get("host");
    const protocol = headerList.get("x-forwarded-proto") || "http";
    redirect(`${protocol}://${host}${HRKPIS_LOGIN_PATH}`);
  }

  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col font-sans">{children}</body>
    </html>
  );
}
